name: Custom Event Workflow

on:
  repository_dispatch:
    types: [custom-event]

jobs:
  custom-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run API Scraper
        run: python api_scraper.py
